{
  "arch": "x86_64",
  "build": "py39hd77b12b_1",
  "build_number": 1,
  "channel": "https://repo.anaconda.com/pkgs/main/win-64",
  "constrains": [],
  "depends": [
    "python >=3.9,<3.10.0a0",
    "vc >=14.1,<15.0a0",
    "vs2015_runtime >=14.16.27012,<15.0a0"
  ],
  "extracted_package_dir": "C:\\Users\\twcro\\AppData\\Local\\ESRI\\conda\\pkgs\\pyodbc-4.0.32-py39hd77b12b_1",
  "features": "",
  "files": [
    "Lib/site-packages/pyodbc-4.0.32.dist-info/INSTALLER",
    "Lib/site-packages/pyodbc-4.0.32.dist-info/LICENSE.txt",
    "Lib/site-packages/pyodbc-4.0.32.dist-info/METADATA",
    "Lib/site-packages/pyodbc-4.0.32.dist-info/RECORD",
    "Lib/site-packages/pyodbc-4.0.32.dist-info/REQUESTED",
    "Lib/site-packages/pyodbc-4.0.32.dist-info/WHEEL",
    "Lib/site-packages/pyodbc-4.0.32.dist-info/direct_url.json",
    "Lib/site-packages/pyodbc-4.0.32.dist-info/top_level.txt",
    "Lib/site-packages/pyodbc.cp39-win_amd64.pyd",
    "pyodbc.pyi",
    ".nonadmin"
  ],
  "fn": "pyodbc-4.0.32-py39hd77b12b_1.conda",
  "license": "MIT",
  "license_family": "MIT",
  "link": {
    "source": "C:\\Users\\twcro\\AppData\\Local\\ESRI\\conda\\pkgs\\pyodbc-4.0.32-py39hd77b12b_1",
    "type": 1
  },
  "md5": "46aeb523d6d32b1245a9915ad61ab7bf",
  "name": "pyodbc",
  "package_tarball_full_path": "C:\\Users\\twcro\\AppData\\Local\\ESRI\\conda\\pkgs\\pyodbc-4.0.32-py39hd77b12b_1.conda",
  "paths_data": {
    "paths": [
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/INSTALLER",
        "path_type": "hardlink",
        "sha256": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "sha256_in_prefix": "d0edee15f91b406f3f99726e44eb990be6e34fd0345b52b910c568e0eef6a2a8",
        "size_in_bytes": 5
      },
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/LICENSE.txt",
        "path_type": "hardlink",
        "sha256": "9859c85770c91b7866b0f769c938e36d64d0260141b529b947b4ead96883eab4",
        "sha256_in_prefix": "9859c85770c91b7866b0f769c938e36d64d0260141b529b947b4ead96883eab4",
        "size_in_bytes": 868
      },
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/METADATA",
        "path_type": "hardlink",
        "sha256": "517542311f9b10420ad873c88fadb0893b28828a565bfca32ff989cf35176a65",
        "sha256_in_prefix": "517542311f9b10420ad873c88fadb0893b28828a565bfca32ff989cf35176a65",
        "size_in_bytes": 2283
      },
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/RECORD",
        "path_type": "hardlink",
        "sha256": "41bbce657d4684bcb281ad185bd145a0f6b976f4c5d7a158b8d1e53c21194e9d",
        "sha256_in_prefix": "41bbce657d4684bcb281ad185bd145a0f6b976f4c5d7a158b8d1e53c21194e9d",
        "size_in_bytes": 825
      },
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/REQUESTED",
        "path_type": "hardlink",
        "sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "sha256_in_prefix": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
        "size_in_bytes": 0
      },
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/WHEEL",
        "path_type": "hardlink",
        "sha256": "7d571594bce2f021a2fd497cbe331d9fc804476e5d9f918183d13a93dcf8d7e6",
        "sha256_in_prefix": "7d571594bce2f021a2fd497cbe331d9fc804476e5d9f918183d13a93dcf8d7e6",
        "size_in_bytes": 100
      },
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/direct_url.json",
        "path_type": "hardlink",
        "sha256": "cd45ba09a314ebc299504bba9735ca28879960ef6ab163788f0991c13e2076d2",
        "sha256_in_prefix": "cd45ba09a314ebc299504bba9735ca28879960ef6ab163788f0991c13e2076d2",
        "size_in_bytes": 66
      },
      {
        "_path": "Lib/site-packages/pyodbc-4.0.32.dist-info/top_level.txt",
        "path_type": "hardlink",
        "sha256": "df48ef61c0ae97aff0036e8e4f9734ebc1801f3a902e977d59f4349924ac0d35",
        "sha256_in_prefix": "df48ef61c0ae97aff0036e8e4f9734ebc1801f3a902e977d59f4349924ac0d35",
        "size_in_bytes": 7
      },
      {
        "_path": "Lib/site-packages/pyodbc.cp39-win_amd64.pyd",
        "path_type": "hardlink",
        "sha256": "f8ae31b4ba55e99275636bb909fc180ade0334ef1239f3284f0be1ec1f95b905",
        "sha256_in_prefix": "f8ae31b4ba55e99275636bb909fc180ade0334ef1239f3284f0be1ec1f95b905",
        "size_in_bytes": 153088
      },
      {
        "_path": "pyodbc.pyi",
        "path_type": "hardlink",
        "sha256": "9554eb8eabb09e50512afa693d2f8289f203c854590e4c74dd11a30d9a3fad7a",
        "sha256_in_prefix": "9554eb8eabb09e50512afa693d2f8289f203c854590e4c74dd11a30d9a3fad7a",
        "size_in_bytes": 13102
      }
    ],
    "paths_version": 1
  },
  "platform": "win32",
  "requested_spec": "defaults/win-64::pyodbc==4.0.32=py39hd77b12b_1",
  "sha256": "9f3074e8b3c2fadfd001d02403684f6701d46f52ee47e345d8c890e5f23b400e",
  "size": 74378,
  "subdir": "win-64",
  "timestamp": 1647426221863,
  "track_features": "",
  "url": "https://repo.anaconda.com/pkgs/main/win-64/pyodbc-4.0.32-py39hd77b12b_1.conda",
  "version": "4.0.32"
}